Created REST API for Get Reviews by Product ID
bagisto/rest-api pull request #331
Opened 2024-06-29 10:23 UTC by akashcsoni

**New enhancements added in product review REST API**

2024-07-08 05:05 UTC, devansh-webkul requested changes

2024-07-08 05:05 UTC, devansh-webkul commented on src/Http/Controllers/V1/Shop/Catalog/ProductReviewController.php
> +        }
Can we simplify this and use the parent built-in method?

2024-07-08 05:05 UTC, devansh-webkul commented on src/Resources/lang/en/app.php
> +                    'get-success'       => 'Get reviews by product successfully.',
Please provide translations for all languages.

2024-07-08 05:05 UTC, devansh-webkul commented on src/Routes/V1/Shop/catalog-routes.php
> +});
We already have product prefix group in top. Use that group.

2024-07-18 13:06 UTC, akashcsoni commented
Hello @devansh-webkul 

I've Updated the code as you suggested.
Please review and inform me if anything else is needed.

Thanks

2024-09-25 05:22 UTC, devansh-webkul commented
Hello,

Thank you for your efforts on this pull request. However, at this time, we won't be merging it as we do not currently require this endpoint. If the need arises in the future, we will likely handle it internally.

2024-09-25 05:22 UTC, closed without merging